<?php declare(strict_types=1);
require __DIR__.'/bootstrap.php';
use App\Auth; use App\Repository;
Auth::requireLogin();
$page=$_GET['page']??'dashboard'; $error=null; $notice=null; $rulesPage=max(1,(int)($_GET['rules_page']??1)); $eventsPage=max(1,(int)($_GET['events_page']??1));
if($_SERVER['REQUEST_METHOD']==='POST'){try{Auth::verifyCsrf($_POST['csrf']??null);$action=$_POST['action']??'';if($action==='logout'){Auth::logout();header('Location:/login.php');exit;}if($action==='save_integration'){
            $submittedGeminiKey=trim((string)($_POST['gemini_api_key']??''));
            if($submittedGeminiKey!=='') Repository::saveIntegration('gemini_api_key', $submittedGeminiKey);
            Repository::saveIntegration('gemini_model', trim((string)($_POST['gemini_model']??'gemini-2.5-flash')));
            $notice='Integração do Google Gemini atualizada com segurança.';
        }
        if($action==='delete_rule'){Repository::deleteRule((int)$_POST['id']);$notice='Regra removida com sucesso.';}if($action==='save_rule'){Repository::saveRule(array_merge($_POST,['remove_links'=>isset($_POST['remove_links']),'remove_emojis'=>isset($_POST['remove_emojis']),'translation_enabled'=>isset($_POST['translation_enabled']),'translation_fallback_original'=>isset($_POST['translation_fallback_original']),'enabled'=>isset($_POST['enabled'])]));$notice='Nova regra publicada.';}if($action==='update_rule'){Repository::updateRule((int)$_POST['id'],array_merge($_POST,['remove_links'=>isset($_POST['remove_links']),'remove_emojis'=>isset($_POST['remove_emojis']),'translation_enabled'=>isset($_POST['translation_enabled']),'translation_fallback_original'=>isset($_POST['translation_fallback_original']),'enabled'=>isset($_POST['enabled'])]));$notice='Regra atualizada e aplicada ao trabalhador.';}}catch(Throwable $e){$error=App\ErrorTranslator::message($e, 'a operação solicitada');}}
$credentials=Repository::credentials();$connectedPhone=(string)($credentials['telegram_phone']??'');if($connectedPhone!==''&&$connectedPhone[0]!=='+')$connectedPhone='+'.$connectedPhone;$rules=Repository::rules($rulesPage,20);$rulesTotal=Repository::rulesTotal();$events=Repository::events($eventsPage,20);$eventsTotal=Repository::eventsTotal();$stats=Repository::overview();$status=Repository::workerStatus();$editRule=isset($_GET['edit'])?Repository::rule((int)$_GET['edit']):null;$formRule=$editRule?:['source_chat'=>'','trigger_text'=>'','destination_chat'=>'','media_mode'=>'previous_photo','translation_provider'=>'none','translation_target_language'=>'pt-BR','remove_links'=>1,'remove_emojis'=>1,'custom_removals'=>'','translation_enabled'=>0,'translation_fallback_original'=>1,'enabled'=>1];
function sh(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');} function paginas(int $page,int $total,string $param):string { $pages=max(1,(int)ceil($total/20)); if($pages<=1)return ''; $out='<nav class="pagination" aria-label="Navegação de páginas">'; for($i=1;$i<=$pages;$i++){ $query=$_GET; $query[$param]=$i; $out.='<a class="'.($i===$page?'current':'').'" href="?'.sh(http_build_query($query)).'">'.$i.'</a>'; } return $out.'</nav>'; }
$active=$page==='dashboard'?'dashboard':$page;
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Telegram Router · Workspace</title><link rel="stylesheet" href="/assets/saas.css"></head><body><div class="saas-shell"><aside class="saas-sidebar"><div class="saas-brand"><span class="saas-logo">↯</span><div><b>Telegram Router</b><small>Automação inteligente</small></div></div><div class="saas-nav-label">PAINEL</div><nav class="saas-nav"><a class="<?=$active==='dashboard'?'active':''?>" href="/?page=dashboard"><span class="nav-icon">⌂</span>Visão geral</a><a class="<?=$active==='rules'?'active':''?>" href="/?page=rules"><span class="nav-icon">≋</span>Regras de roteamento</a><a class="<?=$active==='events'?'active':''?>" href="/?page=events"><span class="nav-icon">◷</span>Atividade</a><a class="<?=$active==='integrations'?'active':''?>" href="/?page=integrations"><span class="nav-icon">◇</span>Integrações</a><a href="/connect.php"><span class="nav-icon">♢</span>Conectar Telegram</a></nav><div class="saas-bottom"><div class="saas-status"><i></i>Serviço protegido</div></div></aside><div class="saas-main"><header class="saas-topbar"><div class="saas-user"><span class="saas-avatar">AN</span><span>Anderson</span><?php if($connectedPhone!==''): ?><span class="connected-phone">Telegram: <?=sh($connectedPhone)?></span><?php endif; ?><form method="post"><input type="hidden" name="csrf" value="<?=sh(Auth::csrf())?>"><input type="hidden" name="action" value="logout"><button class="saas-logout">Sair</button></form></div></header><main class="saas-content"><?php if($error):?><div class="saas-flash error"><?=sh($error)?></div><?php endif;?><?php if($notice):?><div class="saas-flash success"><?=sh($notice)?></div><?php endif;?><?php if($page==='rules'):?><div class="saas-heading"><div><span class="saas-kicker">AUTOMAÇÃO</span><h1>Regras de roteamento</h1><p>Defina exatamente quando uma mensagem deve ser tratada e para onde será enviada.</p></div><div class="saas-heading-actions"><a class="saas-secondary" href="/?page=dashboard">← Visão geral</a><a class="saas-primary" href="#nova-regra">+ Criar regra</a></div></div>
<section class="routing-flow"><div><span class="flow-number">01</span><b>Origem</b><small>Onde a mensagem chega</small></div><span class="flow-arrow">→</span><div><span class="flow-number">02</span><b>Gatilho</b><small>O que ativa a regra</small></div><span class="flow-arrow">→</span><div><span class="flow-number">03</span><b>Destino</b><small>Para onde enviar</small></div></section>
<div class="rules-columns"><section class="saas-card saas-form-card routing-form" id="nova-regra"><div class="saas-card-head"><div><span class="saas-kicker"><?= $editRule?'EDIÇÃO DE REGRA':'NOVA CONFIGURAÇÃO' ?></span><h2><?= $editRule?'Atualizar regra de roteamento':'Quando esta regra for acionada' ?></h2><p>Os campos abaixo serão avaliados pelo trabalhador em tempo real.</p></div><span class="form-status"><i></i>Pronta para ativar</span></div><form method="post"><input type="hidden" name="csrf" value="<?=sh(Auth::csrf())?>"><input type="hidden" name="action" value="<?=$editRule?'update_rule':'save_rule'?>"><?php if($editRule):?><input type="hidden" name="id" value="<?=sh($editRule['id'])?>"><?php endif;?><div class="form-section-title">01 · Identificação dos canais</div><div class="saas-form-grid"><label>Canal ou grupo de origem<span class="field-help">Aceita ID numérico, @username ou nome público.</span><input name="source_chat" value="<?=sh($formRule['source_chat'])?>" placeholder="@canal_origem ou -100…" required></label><label>Canal ou grupo de destino<span class="field-help">A conta Telegram precisa ter acesso ao destino.</span><input name="destination_chat" value="<?=sh($formRule['destination_chat'])?>" placeholder="@meu_canal ou -100…" required></label></div><div class="form-section-title">02 · Condição de acionamento</div><div class="saas-form-grid"><label class="field-wide">Texto que deve aparecer na mensagem<span class="field-help">A comparação não diferencia letras maiúsculas e minúsculas.</span><input name="trigger_text" value="<?=sh($formRule['trigger_text'])?>" placeholder="Ex.: CUPOM, OFERTA, SINAL…" required></label><label class="activation-field">Estado inicial<span class="field-help">Você pode pausar a regra depois na configuração.</span><span class="activation-toggle"><input type="checkbox" name="enabled" checked> Ativar imediatamente</span></label></div><div class="form-section-title">03 · Tratamento do conteúdo</div>
<div class="content-treatment">
  <div class="treatment-block treatment-media">
    <div class="treatment-block-head"><span class="treatment-icon">▣</span><div><b>Formato enviado</b><small>Escolha o conteúdo que chegará ao destino.</small></div></div>
    <label>Conteúdo enviado<select name="media_mode"><option value="previous_photo" <?=$formRule['media_mode']==='previous_photo'?'selected':''?>>Imagem Anterior + Legenda</option><option value="current_media" <?=$formRule['media_mode']==='current_media'?'selected':''?>>Mídia da mensagem + legenda</option><option value="text_only" <?=$formRule['media_mode']==='text_only'?'selected':''?>>Somente texto</option></select></label>
  </div>
  <div class="treatment-block treatment-translation">
    <div class="treatment-block-head"><span class="treatment-icon">文</span><div><b>Tradução</b><small>Converta a mensagem antes do envio.</small></div></div>
    <label>Serviço de tradução<select name="translation_provider"><option value="none" <?=$formRule['translation_provider']==='none'?'selected':''?>>Não traduzir</option><option value="libretranslate" <?=$formRule['translation_provider']==='libretranslate'?'selected':''?>>LibreTranslate</option><option value="gemini" <?=$formRule['translation_provider']==='gemini'?'selected':''?>>Google Gemini</option></select></label>
    <label>Idioma de destino<input name="translation_target_language" value="<?=sh($formRule['translation_target_language'])?>" placeholder="pt-BR"></label>
  </div>
  <div class="treatment-block treatment-removals">
    <div class="treatment-block-head"><span class="treatment-icon">⌫</span><div><b>Remoções personalizadas</b><small>Separe os textos ou números com ponto e vírgula (;). Todos os itens serão retirados da mensagem.</small></div></div>
    <label>Textos ou números para remover<textarea name="custom_removals" rows="4" placeholder="Exemplo: Assine nosso canal; 12345; PATROCINADO"><?=sh($formRule['custom_removals']??'')?></textarea></label>
  </div>
  <div class="treatment-block treatment-cleaning">
    <div class="treatment-block-head"><span class="treatment-icon">✦</span><div><b>Opções de limpeza</b><small>Defina quais elementos serão removidos automaticamente.</small></div></div>
    <div class="treatment-checks"><label><input type="checkbox" name="remove_links" <?=!empty($formRule['remove_links'])?'checked':''?>> Remover links</label><label><input type="checkbox" name="remove_emojis" <?=!empty($formRule['remove_emojis'])?'checked':''?>> Remover emojis</label><label><input type="checkbox" name="translation_enabled" <?=!empty($formRule['translation_enabled'])?'checked':''?>> Ativar tradução</label><label><input type="checkbox" name="translation_fallback_original" <?=!empty($formRule['translation_fallback_original'])?'checked':''?>> Preservar original se falhar</label></div>
  </div>
</div>
<input type="hidden" name="translation_source_language" value="auto"><div class="saas-actions"><span class="form-note">A regra será salva com segurança no banco de dados.</span><button class="saas-primary"><?= $editRule?'Aplicar alterações →':'Salvar e ativar regra →' ?></button></div></form></section>
<section class="saas-card routing-list rules-panel">
  <div class="saas-card-head rules-panel-head"><div><span class="saas-kicker">REGRAS CONFIGURADAS</span><h2>Fluxos em operação</h2><p><?=sh($rulesTotal)?> <?=($rulesTotal===1?'regra configurada':'regras configuradas')?> neste ambiente.</p></div><div class="rules-panel-meta"><span class="rules-count"><b><?=sh($stats['active'])?></b> ativas</span><span class="rules-page-label">Página <?=sh($rulesPage)?></span></div></div>
  <?php if(!$rules):?><div class="saas-empty rules-empty"><span class="rules-empty-icon">≋</span><h3>Nenhuma regra configurada</h3><p>Crie uma regra para começar a encaminhar mensagens automaticamente.</p><a class="saas-primary" href="#nova-regra">+ Criar primeira regra</a></div><?php endif;?>
  <?php foreach($rules as $r):?><article class="routing-rule rule-card <?=((int)$r['enabled']?'':'paused')?>">
    <div class="rule-card-top"><div class="routing-rule-status"><span class="saas-dot <?=((int)$r['enabled']?'':'off')?>"></span><?=((int)$r['enabled']?'ATIVA':'PAUSADA')?></div><span class="rule-id">REGRA #<?=sh($r['id'])?></span></div>
    <div class="routing-path rule-route"><div><small>ORIGEM</small><b title="<?=sh($r['source_chat'])?>"><?=sh($r['source_chat'])?></b></div><span class="rule-route-arrow">→</span><div><small>GATILHO</small><b class="trigger-chip" title="<?=sh($r['trigger_text'])?>"><?=sh($r['trigger_text'])?></b></div><span class="rule-route-arrow">→</span><div><small>DESTINO</small><b title="<?=sh($r['destination_chat'])?>"><?=sh($r['destination_chat'])?></b></div></div>
    <div class="rule-card-bottom"><div class="rule-tags"><span><?=sh(match($r['media_mode']){'previous_photo'=>'Foto anterior','current_media'=>'Mídia atual','text_only'=>'Somente texto',default=>$r['media_mode']})?></span><span><?=((int)$r['remove_links']?'Links removidos':'Links preservados')?></span><span><?=((int)$r['remove_emojis']?'Emojis removidos':'Emojis preservados')?></span><?=trim((string)($r['custom_removals']??''))!==''?'<span>Remoções personalizadas</span>':''?></div><div class="rule-actions"><a class="saas-secondary rule-edit" href="/?page=rules&amp;edit=<?=sh($r['id'])?>">Editar</a><form method="post" class="routing-delete"><input type="hidden" name="csrf" value="<?=sh(Auth::csrf())?>"><input type="hidden" name="action" value="delete_rule"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="saas-danger" title="Excluir regra">Excluir</button></form></div></div>
  </article><?php endforeach;?><?=paginas($rulesPage,$rulesTotal,'rules_page')?></section></div><?php elseif($page==='events'):?><div class="saas-heading"><div><span class="saas-kicker">CENTRAL DE ACOMPANHAMENTO</span><h1>Atividades</h1><p>Veja o que o trabalhador recebeu, processou e encaminhou.</p></div><div class="saas-heading-actions"><a class="saas-secondary" href="/?page=dashboard">← Visão geral</a><a class="saas-primary" href="/?page=rules">Gerenciar regras →</a></div></div>
<section class="activity-summary"><div><span class="activity-summary-label">EVENTOS REGISTRADOS</span><strong><?=sh($eventsTotal)?></strong><small>20 por página</small></div><div><span class="activity-summary-label">ENCAMINHADAS</span><strong class="activity-good"><?=sh($stats['forwarded']??0)?></strong><small>entregas concluídas</small></div><div><span class="activity-summary-label">COM FALHA</span><strong class="activity-bad"><?=sh($stats['failed']??0)?></strong><small>verifique os detalhes</small></div><div><span class="activity-summary-label">IGNORADAS</span><strong class="activity-warn"><?=sh($stats['skipped']??0)?></strong><small>sem encaminhamento</small></div></section>
<section class="saas-card activity-card"><div class="saas-card-head activity-card-head"><div><span class="saas-kicker">REGISTRO OPERACIONAL</span><h2>Histórico de processamento</h2><p>Cada linha representa uma tentativa única de processamento.</p></div><div class="activity-legend"><span><i class="legend-good"></i>Concluída</span><span><i class="legend-bad"></i>Falhou</span><span><i class="legend-warn"></i>Ignorada</span></div></div><?php if(!$events):?><div class="activity-empty"><span>◷</span><h3>Nenhuma atividade registrada</h3><p>O trabalhador continuará conectado e mostrará aqui a próxima mensagem processada.</p></div><?php else:?><div class="activity-list"><?php foreach($events as $e):?><article class="activity-item"><div class="activity-status-dot <?=sh(match($e['status']){'forwarded'=>'Encaminhada','failed'=>'Falhou','skipped'=>'Ignorada','processing'=>'Processando',default=>'Registrada'})?>"></div><div class="activity-main"><div class="activity-item-top"><b><?=sh(match($e['status']){'forwarded'=>'Mensagem encaminhada','failed'=>'Falha no encaminhamento','skipped'=>'Mensagem ignorada','processing'=>'Processando mensagem',default=>'Evento registrado'})?></b><time><?=sh(dataHoraBrasil($e['created_at']))?></time></div><div class="activity-route"><span><?=sh($e['source_chat'])?></span><strong>#<?=sh($e['message_id'])?></strong><span class="route-arrow">→</span><span><?=sh($e['destination_chat'])?></span></div><div class="activity-details"><span>Gatilho: <b><?=sh($e['trigger_text'])?></b></span><span class="activity-badge <?=sh(match($e['status']){'forwarded'=>'Encaminhada','failed'=>'Falhou','skipped'=>'Ignorada','processing'=>'Processando',default=>'Registrada'})?>"><?=sh(match($e['status']){'forwarded'=>'Concluída','failed'=>'Falhou','skipped'=>'Ignorada','processing'=>'Em processamento',default=>$e['status']})?></span></div><?php if($e['status']==='failed' && !empty($e['details'])):?><div class="activity-error"><b>Detalhes da falha</b><span><?=sh($e['details'])?></span></div><?php elseif($e['status']==='skipped' && !empty($e['details'])):?><div class="activity-note"><?=sh($e['details'])?></div><?php endif;?></div></article><?php endforeach;?></div><?php endif;?><?=paginas($eventsPage,$eventsTotal,'events_page')?></section><?php elseif($page==='integrations'):
$geminiKey=Repository::integration('gemini_api_key'); $geminiModel=Repository::integration('gemini_model')?:'gemini-2.5-flash';
?><div class="saas-heading"><div><span class="saas-kicker">SERVIÇOS EXTERNOS</span><h1>Integrações</h1><p>Configure os serviços usados pelo roteador sem editar arquivos do servidor.</p></div><div class="saas-heading-actions"><a class="saas-secondary" href="/?page=dashboard">← Visão geral</a></div></div>
<section class="saas-card" style="max-width:860px"><div class="saas-card-head"><div><span class="saas-kicker">GOOGLE GEMINI AI STUDIO</span><h2>Tradução de mensagens</h2><p>A chave é armazenada cifrada com AES-256-GCM e pode ser substituída a qualquer momento.</p></div><span class="form-status"><i></i><?= $geminiKey?'Configurado':'Não configurado' ?></span></div><form method="post"><input type="hidden" name="csrf" value="<?=sh(Auth::csrf())?>"><input type="hidden" name="action" value="save_integration"><div class="saas-form-grid"><label class="field-wide">Chave da API do Gemini<span class="field-help">Cole uma nova chave para substituir a atual. Deixe em branco para manter a chave existente.</span><input name="gemini_api_key" type="password" placeholder="Cole a chave do Google AI Studio"></label><label>Modelo<span class="field-help">Modelo usado nas traduções.</span><select name="gemini_model"><option value="gemini-3.6-flash" <?=$geminiModel==='gemini-3.6-flash'?'selected':''?>>Gemini 3.6 Flash</option><option value="gemini-2.5-flash" <?=$geminiModel==='gemini-2.5-flash'?'selected':''?>>Gemini 2.5 Flash</option><option value="gemini-2.0-flash" <?=$geminiModel==='gemini-2.0-flash'?'selected':''?>>Gemini 2.0 Flash</option></select></label></div><div class="saas-actions"><span class="form-note">Depois, selecione Google Gemini nas regras de roteamento e ative a tradução.</span><button class="saas-primary">Salvar integração →</button></div></form></section>
<?php else:?><div class="saas-heading"><div><span class="saas-kicker">CENTRAL DE OPERAÇÃO</span><h1>Visão geral</h1><p>Acompanhe a conexão, as regras e cada tentativa de encaminhamento.</p></div><div class="saas-heading-actions"><a class="saas-secondary" href="/?page=events">Ver atividade</a><a class="saas-primary" href="/?page=rules">+ Nova regra</a></div></div>
<section class="overview-status <?=($status['status']??'desconectado')==='conectado'?'is-good':'is-alert'?>"><div class="overview-status-icon"><i></i></div><div><span class="saas-kicker">ESTADO DO SERVIÇO</span><h2><?=sh(match($status['status']??'desconectado'){'conectado'=>'Conectado','processando'=>'Processando','reconectando'=>'Reconectando','erro'=>'Erro','desconectado'=>'Desconectado',default=>'Estado não identificado'})?></h2><p><?=($status['status']??'')==='conectado'?'A conexão está ativa e o trabalhador está pronto para receber novas mensagens.':'O trabalhador não está em condição normal de processamento. Consulte os detalhes abaixo.'?></p></div><div class="overview-status-meta"><span>Última verificação</span><b><?=sh(dataHoraBrasil($status['last_activity_at']??null))?></b><a href="/connect.php">Gerenciar conexão →</a></div></section>
<?php if(($status['status']??'')==='erro' && !empty($status['last_error'])):?><section class="overview-alert"><b>Falha registrada no trabalhador</b><p><?=sh($status['last_error'])?></p><small>A conexão permanece monitorada. Verifique a conta e os canais configurados antes de tentar novamente.</small></section><?php endif;?>
<section class="saas-metrics overview-metrics"><div class="saas-metric"><div class="saas-metric-label">REGRAS ATIVAS <span class="saas-metric-icon">≋</span></div><strong><?=sh($stats['active'])?></strong><small><?=sh($stats['total'])?> regras cadastradas</small></div><div class="saas-metric"><div class="saas-metric-label">ENCAMINHADAS HOJE <span class="saas-metric-icon">↗</span></div><strong><?=sh($stats['forwarded']??0)?></strong><small>entregas concluídas</small></div><div class="saas-metric"><div class="saas-metric-label">TENTATIVAS COM FALHA <span class="saas-metric-icon danger">!</span></div><strong class="metric-danger"><?=sh($stats['failed']??0)?></strong><small>exigem atenção</small></div><div class="saas-metric"><div class="saas-metric-label">EVENTOS PROCESSADOS <span class="saas-metric-icon">◷</span></div><strong><?=sh(($stats['forwarded']??0)+($stats['failed']??0)+($stats['skipped']??0))?></strong><small><?=sh($stats['skipped']??0)?> ignorados pelas regras</small></div></section>
<div class="saas-grid overview-grid"><section class="saas-card"><div class="saas-card-head"><div><span class="saas-kicker">MONITORAMENTO</span><h2>Últimas movimentações</h2><p>O que aconteceu recentemente no roteador.</p></div><a class="saas-link" href="/?page=events">Abrir histórico →</a></div><?php if(!$events):?><div class="saas-empty">Ainda não há mensagens processadas. O trabalhador continuará conectado e aguardando novos eventos.</div><?php else:?><div class="saas-table-wrap"><table class="saas-table"><thead><tr><th>Origem</th><th>Destino</th><th>Resultado</th><th>Quando</th></tr></thead><tbody><?php foreach(array_slice($events,0,6) as $e):?><tr><td><?=sh($e['source_chat'])?> · #<?=sh($e['message_id'])?></td><td><?=sh($e['destination_chat'])?></td><td><span class="saas-badge <?=sh(match($e['status']){'forwarded'=>'Encaminhada','failed'=>'Falhou','skipped'=>'Ignorada','processing'=>'Processando',default=>'Registrada'})?>"><?=sh(match($e['status']){'forwarded'=>'Encaminhada','failed'=>'Falhou','skipped'=>'Ignorada','processing'=>'Processando',default=>$e['status']})?></span></td><td><?=sh(dataHoraBrasil($e['created_at']))?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section><section class="saas-card"><div class="saas-card-head"><div><span class="saas-kicker">CONFIGURAÇÃO</span><h2>Regras em operação</h2><p>Resumo das origens e destinos ativos.</p></div><a class="saas-link" href="/?page=rules">Gerenciar →</a></div><?php foreach(array_slice($rules,0,5) as $r):?><div class="saas-rule"><div class="saas-rule-top"><b><span class="saas-dot <?=((int)$r['enabled']?'':'off')?>"></span><?=sh($r['source_chat'])?></b><span class="rule-state"><?=((int)$r['enabled']?'Ativa':'Pausada')?></span></div><p><?=sh($r['trigger_text'])?> <span class="rule-arrow">→</span> <?=sh($r['destination_chat'])?></p></div><?php endforeach;if(!$rules):?><div class="saas-empty">Nenhuma regra criada. Configure a primeira para iniciar os encaminhamentos.</div><?php endif;?></section></div>
<section class="saas-card overview-guide"><div><span class="saas-kicker">COMO FUNCIONA</span><h2>O trabalhador permanece pronto</h2><p>Sem mensagens, o sistema não entra em espera: ele continua conectado, monitorando os canais e preparado para processar o próximo evento.</p></div><div class="guide-points"><span><i>1</i>Recebe a mensagem</span><span><i>2</i>Valida a regra</span><span><i>3</i>Encaminha ao destino</span></div></section><?php endif;?></main></div></div><script src="/assets/live.js" defer></script><script src="/assets/toast.js" defer></script></body></html>
