<?php declare(strict_types=1);

/*
 * Integrations UI v9.
 * One runtime, one stylesheet, one behavior file.
 * Keeps provider forms/tests generated by the functional integrations patch.
 */

$path = __DIR__.'/index.php';
if (!is_file($path)) {
    fwrite(STDERR, "INTEGRATIONS_UI_V9_INDEX_MISSING\n");
    exit(1);
}

$source = (string)file_get_contents($path);

// Remove the old dedicated integrations stylesheet. v9 owns the module layout.
$source = preg_replace(
    '~<link\b[^>]*href=["\']/assets/integrations-layout\.css[^"\']*["\'][^>]*>~i',
    '',
    $source
) ?? $source;

// Remove prior UI summaries if this runtime is ever applied twice.
$source = preg_replace(
    '~<!-- integrations_ui_v(?:2|5|6|9) -->\s*<section class="(?:integrations-hero-v2|integrations-overview-v5|integrations-summary-v6|integrations-overview-v9)">.*?</section>\s*~s',
    '',
    $source
) ?? $source;

$marker = '<section class="saas-card integrations-connection">';
if (!str_contains($source, $marker)) {
    fwrite(STDERR, "INTEGRATIONS_UI_V9_MARKER_MISSING\n");
    exit(1);
}

$overview = <<<'HTML'
<!-- integrations_ui_v9 -->
<section class="integrations-overview-v9">
  <div class="integrations-overview-v9-copy">
    <span class="saas-kicker">CENTRAL DE INTEGRAÇÕES</span>
    <h2>Serviços e credenciais</h2>
    <p>Gerencie o Telegram e os provedores de tradução em um único lugar. Cada provedor mantém sua própria chave, teste de conexão, data/hora e diagnóstico.</p>
  </div>
  <div class="integrations-overview-v9-stats">
    <div class="integrations-overview-v9-stat">
      <span>Chaves salvas</span>
      <strong><?=((!empty($azureKey)?1:0)+(!empty($geminiKey)?1:0)+(!empty($googleCloudKey)?1:0))?> / 3</strong>
    </div>
    <div class="integrations-overview-v9-stat">
      <span>Testes válidos</span>
      <strong><?=((!empty($azureTest['last_test_ok'])?1:0)+(!empty($geminiTest['last_test_ok'])?1:0)+(!empty($googleCloudTest['last_test_ok'])?1:0))?> / 3</strong>
    </div>
    <div class="integrations-overview-v9-stat">
      <span>Telegram</span>
      <strong><?=$connectedPhone!==''?'Online':'Offline'?></strong>
    </div>
  </div>
</section>
HTML;

$source = str_replace($marker, $overview."\n".$marker, $source, $insertCount);
if ($insertCount !== 1) {
    fwrite(STDERR, "INTEGRATIONS_UI_V9_INSERT_FAILED\n");
    exit(1);
}

// Normalize the section title produced by the functional integrations patch.
$source = preg_replace(
    '~<div class="integrations-section-heading">.*?</div><div class="translation-provider-grid">~s',
    '<div class="integrations-section-heading"><div><span class="saas-kicker">PROVEDORES DE TRADUÇÃO</span><h2>Credenciais e conexão</h2><p>Clique no card para expandir ou recolher. O teste, a data/hora e o estado da chave permanecem dentro do respectivo provedor.</p></div></div><div class="translation-provider-grid">',
    $source,
    1,
    $headingCount
) ?? $source;
if ($headingCount !== 1) {
    fwrite(STDERR, "INTEGRATIONS_UI_V9_HEADING_FAILED\n");
    exit(1);
}

// Keep exactly one current integrations behavior bundle.
$source = preg_replace(
    "~<script\b[^>]*src=[\"'][^\"']*integrations-(?:v2|ui-v4|ui-v5|ui-v6|v9)\.js[^\"']*[\"'][^>]*></script>~i",
    '',
    $source
) ?? $source;
$source = str_replace(
    '</body>',
    '<script src="/assets/brand/integrations-v9.js?v=1" defer></script></body>',
    $source
);

if (@file_put_contents($path, $source) === false) {
    fwrite(STDERR, "INTEGRATIONS_UI_V9_WRITE_FAILED\n");
    exit(1);
}

$verify = (string)file_get_contents($path);
if (
    !str_contains($verify, 'integrations_ui_v9') ||
    !str_contains($verify, '/assets/brand/integrations-v9.js?v=1') ||
    str_contains($verify, '/assets/integrations-layout.css')
) {
    fwrite(STDERR, "INTEGRATIONS_UI_V9_VERIFY_FAILED\n");
    exit(1);
}

echo "INTEGRATIONS_UI_V9_APPLIED\n";
